/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@ionic/core';
import 'ionicons';


export namespace Components {

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface AuthButton {}
  interface AuthButtonAttributes extends StencilHTMLAttributes {}

  interface PageHome {}
  interface PageHomeAttributes extends StencilHTMLAttributes {}

  interface PageTabs {}
  interface PageTabsAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AppRoot': Components.AppRoot;
    'AuthButton': Components.AuthButton;
    'PageHome': Components.PageHome;
    'PageTabs': Components.PageTabs;
  }

  interface StencilIntrinsicElements {
    'app-root': Components.AppRootAttributes;
    'auth-button': Components.AuthButtonAttributes;
    'page-home': Components.PageHomeAttributes;
    'page-tabs': Components.PageTabsAttributes;
  }


  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLAuthButtonElement extends Components.AuthButton, HTMLStencilElement {}
  var HTMLAuthButtonElement: {
    prototype: HTMLAuthButtonElement;
    new (): HTMLAuthButtonElement;
  };

  interface HTMLPageHomeElement extends Components.PageHome, HTMLStencilElement {}
  var HTMLPageHomeElement: {
    prototype: HTMLPageHomeElement;
    new (): HTMLPageHomeElement;
  };

  interface HTMLPageTabsElement extends Components.PageTabs, HTMLStencilElement {}
  var HTMLPageTabsElement: {
    prototype: HTMLPageTabsElement;
    new (): HTMLPageTabsElement;
  };

  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement
    'auth-button': HTMLAuthButtonElement
    'page-home': HTMLPageHomeElement
    'page-tabs': HTMLPageTabsElement
  }

  interface ElementTagNameMap {
    'app-root': HTMLAppRootElement;
    'auth-button': HTMLAuthButtonElement;
    'page-home': HTMLPageHomeElement;
    'page-tabs': HTMLPageTabsElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
